"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/eKjuFfUMmH4
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
} from "@/components/ui/card";
import Link from "next/link";
import { PullRequest, Status } from "@/lib/types";
import { useState } from "react";
import { cn } from "@/lib/utils";
import { useHotkeys } from "react-hotkeys-hook";

interface Props {
  pullRequests: PullRequest[];
}

function getColorFromStatus(status: Status) {
  if (status === Status.Merged) {
    return { light: "bg-purple-400", dark: "bg-purple-500" };
  } else if (status === Status.Blocked) {
    return { light: "bg-orange-400", dark: "bg-orange-500" };
  } else if (status === Status.Closed) {
    return { light: "bg-red-400", dark: "bg-red-500" };
  } else {
    return { light: "bg-green-400", dark: "bg-green-500" };
  }
}

export function PullRequests({ pullRequests }: Props) {
  const [selected, setSelected] = useState(0);

  useHotkeys(
    "ArrowDown",
    () => {
      setSelected((selected) => (selected + 1) % pullRequests.length);
    },
    [pullRequests],
  );
  useHotkeys(
    "ArrowUp",
    () => {
      setSelected((selected) =>
        selected - 1 < 0 ? pullRequests.length - 1 : selected - 1,
      );
    },
    [pullRequests],
  );
  useHotkeys("Enter", () => {
    const url = `https://github.com/${pullRequests[selected].repository}/pull/${pullRequests[selected].number}`;
    window.open(url, "_blank");
  });
  return (
    <Card className="w-full max-w-2xl">
      <CardHeader>
        <CardTitle>Latest Pull Requests</CardTitle>
        <CardDescription>
          View your recent pull requests and their status
        </CardDescription>
      </CardHeader>
      <CardContent className="grid gap-4">
        {pullRequests.map((pullRequest, i) => {
          const { light, dark } = getColorFromStatus(pullRequest.status);
          const repoUrl = `https://github.com/${pullRequest.repository}`;
          const url = `${repoUrl}/pull/${pullRequest.number}`;

          return (
            <div
              onMouseEnter={() => setSelected(i)}
              key={`${pullRequest.repository}-${pullRequest.number}`}
              className={cn(
                "flex items-center gap-4 py-2 pl-4",
                i == selected && "bg-gray-100",
              )}
            >
              <div className="flex h-3 w-3">
                <div
                  className={cn(
                    "relative inline-flex h-3 w-3 items-center justify-center rounded-full",
                    dark,
                  )}
                >
                  <span
                    className={cn(
                      "absolute inline-flex h-full w-full animate-ping rounded-full opacity-75",
                      light,
                    )}
                  />
                </div>
              </div>
              <div className="flex-1 text-sm font-medium">
                <Link
                  href={repoUrl}
                  className="text-foreground"
                  prefetch={false}
                >
                  {pullRequest.repository}
                </Link>
              </div>
              <div className="flex-1 text-sm">
                <Link
                  href={url}
                  className="text-muted-foreground"
                  prefetch={false}
                >
                  {pullRequest.title}
                </Link>
              </div>
              <div className="w-24">
                <div className="text-sm text-muted-foreground">
                  #{pullRequest.number}
                </div>
              </div>
            </div>
          );
        })}
      </CardContent>
    </Card>
  );
}
